"""Initial_migration

Revision ID: e76e90efcd4c
Revises: 
Create Date: 2026-01-25 20:49:45.296782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76e90efcd4c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_control_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', 'type', name='unique_ip_type')
    )
    with op.batch_alter_table('access_control_list', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_access_control_list_ip_address'), ['ip_address'], unique=False)

    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('current_add_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chats_telegram_chat_id'), ['telegram_chat_id'], unique=True)

    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('traceback', sa.String(), nullable=True),
    sa.Column('is_traceback_compressed', sa.Boolean(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_logs_module'), ['module'], unique=False)

    op.create_table('media_signatures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(), nullable=False),
    sa.Column('signature', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'signature', name='unique_chat_signature')
    )
    with op.batch_alter_table('media_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_signatures_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_signatures_signature'), ['signature'], unique=False)

    op.create_table('rss_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('target_chat_id', sa.String(), nullable=False),
    sa.Column('last_guid', sa.String(), nullable=True),
    sa.Column('last_published', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('min_interval', sa.Integer(), nullable=True),
    sa.Column('max_interval', sa.Integer(), nullable=True),
    sa.Column('current_interval', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rss_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rss_subscriptions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_rss_subscriptions_url'), ['url'], unique=False)

    op.create_table('system_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_configurations_key'), ['key'], unique=True)

    op.create_table('task_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('task_data', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('scheduled_at', sa.String(), nullable=True),
    sa.Column('started_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('source_chat_id', sa.String(), nullable=True),
    sa.Column('target_chat_id', sa.String(), nullable=True),
    sa.Column('unique_key', sa.String(), nullable=True),
    sa.Column('grouped_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_queue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_queue_grouped_id'), ['grouped_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_queue_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_queue_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_queue_unique_key'), ['unique_key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telegram_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.String(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), nullable=True),
    sa.Column('backup_codes', sa.String(), nullable=True),
    sa.Column('last_otp_token', sa.String(), nullable=True),
    sa.Column('last_otp_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_sessions_token'), ['token'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('chat_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('forward_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'date', name='unique_chat_date_stats')
    )
    with op.batch_alter_table('chat_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_statistics_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_statistics_date'), ['date'], unique=False)

    op.create_table('forward_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_chat_id', sa.Integer(), nullable=False),
    sa.Column('target_chat_id', sa.Integer(), nullable=False),
    sa.Column('enable_rule', sa.Boolean(), nullable=True),
    sa.Column('forward_mode', sa.String(), nullable=True),
    sa.Column('handle_mode', sa.String(), nullable=True),
    sa.Column('message_mode', sa.String(), nullable=True),
    sa.Column('enable_dedup', sa.Boolean(), nullable=True),
    sa.Column('is_ai', sa.Boolean(), nullable=True),
    sa.Column('is_summary', sa.Boolean(), nullable=True),
    sa.Column('is_delete_original', sa.Boolean(), nullable=True),
    sa.Column('is_preview', sa.String(), nullable=True),
    sa.Column('is_original_sender', sa.Boolean(), nullable=True),
    sa.Column('is_original_time', sa.Boolean(), nullable=True),
    sa.Column('is_original_link', sa.Boolean(), nullable=True),
    sa.Column('is_filter_user_info', sa.Boolean(), nullable=True),
    sa.Column('use_bot', sa.Boolean(), nullable=True),
    sa.Column('enable_comment_button', sa.Boolean(), nullable=True),
    sa.Column('enable_delay', sa.Boolean(), nullable=True),
    sa.Column('delay_seconds', sa.Integer(), nullable=True),
    sa.Column('force_pure_forward', sa.Boolean(), nullable=True),
    sa.Column('enable_sync', sa.Boolean(), nullable=True),
    sa.Column('enable_reverse_blacklist', sa.Boolean(), nullable=True),
    sa.Column('enable_reverse_whitelist', sa.Boolean(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('summary_prompt', sa.Text(), nullable=True),
    sa.Column('userinfo_template', sa.String(), nullable=True),
    sa.Column('time_template', sa.String(), nullable=True),
    sa.Column('original_link_template', sa.String(), nullable=True),
    sa.Column('add_mode', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['target_chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forward_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_chat_id', sa.Integer(), nullable=False),
    sa.Column('target_chat_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.ForeignKeyConstraint(['source_chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['target_chat_id'], ['chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(), nullable=True),
    sa.Column('is_regex', sa.Boolean(), nullable=True),
    sa.Column('is_blacklist', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'keyword', 'is_regex', 'is_blacklist', name='unique_rule_keyword_is_regex_is_blacklist')
    )
    op.create_table('media_extensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'extension', name='unique_rule_extension')
    )
    op.create_table('media_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.Boolean(), nullable=True),
    sa.Column('document', sa.Boolean(), nullable=True),
    sa.Column('video', sa.Boolean(), nullable=True),
    sa.Column('audio', sa.Boolean(), nullable=True),
    sa.Column('voice', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_table('push_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('enable_push_channel', sa.Boolean(), nullable=True),
    sa.Column('push_channel', sa.String(), nullable=True),
    sa.Column('media_send_mode', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replace_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'pattern', 'content', name='unique_rule_pattern_content')
    )
    op.create_table('rss_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('enable_rss', sa.Boolean(), nullable=True),
    sa.Column('rss_url', sa.String(), nullable=True),
    sa.Column('check_interval', sa.Integer(), nullable=True),
    sa.Column('last_check_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id')
    )
    op.create_table('rule_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('is_result_compressed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_logs_rule_id'), ['rule_id'], unique=False)

    op.create_table('rule_statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('total_triggered', sa.Integer(), nullable=True),
    sa.Column('success_count', sa.Integer(), nullable=True),
    sa.Column('filtered_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'date', name='unique_rule_date_stats')
    )
    with op.batch_alter_table('rule_statistics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_statistics_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_statistics_rule_id'), ['rule_id'], unique=False)

    op.create_table('rule_syncs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('sync_rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['forward_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rss_config_id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.Column('pattern_type', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rss_config_id'], ['rss_configs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rss_config_id', 'pattern', 'pattern_type', name='unique_rss_pattern')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rss_patterns')
    op.drop_table('rule_syncs')
    with op.batch_alter_table('rule_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_statistics_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_statistics_date'))

    op.drop_table('rule_statistics')
    with op.batch_alter_table('rule_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_logs_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_logs_created_at'))

    op.drop_table('rule_logs')
    op.drop_table('rss_configs')
    op.drop_table('replace_rules')
    op.drop_table('push_configs')
    op.drop_table('media_types')
    op.drop_table('media_extensions')
    op.drop_table('keywords')
    op.drop_table('forward_mappings')
    op.drop_table('forward_rules')
    with op.batch_alter_table('chat_statistics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_statistics_date'))
        batch_op.drop_index(batch_op.f('ix_chat_statistics_chat_id'))

    op.drop_table('chat_statistics')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_sessions_token'))

    op.drop_table('active_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))

    op.drop_table('users')
    with op.batch_alter_table('task_queue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_queue_unique_key'))
        batch_op.drop_index(batch_op.f('ix_task_queue_task_type'))
        batch_op.drop_index(batch_op.f('ix_task_queue_status'))
        batch_op.drop_index(batch_op.f('ix_task_queue_grouped_id'))

    op.drop_table('task_queue')
    with op.batch_alter_table('system_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_configurations_key'))

    op.drop_table('system_configurations')
    with op.batch_alter_table('rss_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rss_subscriptions_url'))
        batch_op.drop_index(batch_op.f('ix_rss_subscriptions_is_active'))

    op.drop_table('rss_subscriptions')
    with op.batch_alter_table('media_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_signatures_signature'))
        batch_op.drop_index(batch_op.f('ix_media_signatures_chat_id'))

    op.drop_table('media_signatures')
    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_logs_module'))
        batch_op.drop_index(batch_op.f('ix_error_logs_level'))
        batch_op.drop_index(batch_op.f('ix_error_logs_created_at'))

    op.drop_table('error_logs')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_telegram_chat_id'))

    op.drop_table('chats')
    with op.batch_alter_table('access_control_list', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_control_list_ip_address'))

    op.drop_table('access_control_list')
    # ### end Alembic commands ###
